name: Node

on:
  pull_request:
  push:
    branches:
      - v2

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-versions:
          - '20.x'

    name: node${{ matrix.node-versions }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up node ${{ matrix.node-versions }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-versions }}

      - name: Install dependencies & build
        run: |
          npm ci
          npm run build --if-present

      - name: Check webpack build changes
        run: |
          bash -c "[[ ! \"`git status --porcelain `\" ]] || ( echo 'Uncommited changes in webpack build' && git status && exit 1 )"
