name: Node

on:
  pull_request:
  push:
    branches:
      - v2

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-versions:
          - '24'

    name: node${{ matrix.node-versions }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up node ${{ matrix.node-versions }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ matrix.node-versions }}

      - name: Install dependencies & build
        run: |
          npm ci
          npm run build --if-present

      - name: Check webpack build changes
        run: |
          bash -c "[[ ! \"`git status --porcelain `\" ]] || ( echo 'Uncommited changes in webpack build' && git status && exit 1 )"
